# Creating baseline equal-wheight model for forming portfolio

In [1]:
%pip install yfinance

Requirement already satisfied: yfinance in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (6.1.2)
Requirement already satisfied: multitasking>=0.0.7 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (2.5.2)
Requirement already satisfied: pandas>=1.3.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (3.0.5)
Requirement already satisfied: peewee>=3.16.2 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (4.4.0)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (4.11.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (7.36.1)
Requirement already satisfied: pytz>=2022.5 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (2.34.2)
Requirement already satisfied: websockets>=13.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/sergei/Documents/programming/nlp-driven-risk-modeling/.conda/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.7.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import yfinance as yf

In [2]:
def get_close_prices(tickers, target_date):
    data = yf.download(
        tickers,
        start=target_date,
        end=target_date + pd.Timedelta(days=14),
        interval="1d",
        auto_adjust=False,
        progress=False,
    )

    if data is None or data.empty:
        raise ValueError("Не удалось получить цены.")

    return data["Adj Close"].iloc[0]

## Testing tickers' price, dividends, portfolio distribution

In [15]:
tickers = ['AAPL', 'MSFT', 'AMZN', 'JPM', 'XOM', 'JNJ', 'WMT', 'CAT', 'NEE', 'KO',
                 'UPS', 'NVDA']
target_date = pd.Timestamp("2026-01-05")

data = yf.download(
    tickers,
    start=target_date,
    end=target_date + pd.Timedelta(days=1),
    interval="1d",
    auto_adjust=False,
    progress=False,
)

close_prices = data["Close"].iloc[0] # type: ignore
print(close_prices)

Ticker
AAPL    267.260010
AMZN    233.059998
CAT     616.099976
JNJ     204.309998
JPM     334.040009
KO       67.940002
MSFT    472.850006
NEE      81.320000
NVDA    188.119995
UPS     102.000000
WMT     112.709999
XOM     125.360001
Name: 2026-01-05 00:00:00, dtype: float64

In [16]:
average_close = close_prices.mean()
variance = close_prices.std()

print(f"Средняя цена закрытия: {average_close:.2f}")
print(f"Дисперсия: {variance:.2f}")

Средняя цена закрытия: 233.76
Дисперсия: 168.41

In [11]:
target_date = pd.Timestamp("2020-05-05")

data = yf.download(
    tickers,
    start=target_date,
    end=target_date + pd.Timedelta(days=1),
    interval="1d",
    auto_adjust=False,
    progress=False,
)

close_prices = data["Close"].iloc[0] # type: ignore
print(close_prices)

Ticker
AAPL     74.389999
AMZN    115.889999
CAT     108.910004
JNJ     149.500000
JPM      92.000000
KO       45.400002
MSFT    180.759995
NEE      57.525002
NVDA      7.343500
UPS      92.709999
WMT      41.576668
XOM      44.830002
Name: 2020-05-05 00:00:00, dtype: float64

In [12]:
average_close = close_prices.mean()
variance = close_prices.std()

print(f"Средняя цена закрытия: {average_close:.2f}")
print(f"Дисперсия: {variance:.2f}")

Средняя цена закрытия: 84.24
Дисперсия: 49.47

## 1 test step of baseline model cycle

**Initializing capital**

In [3]:
initial_capital = 100_000

**Close prices of each portfolios' position**

In [14]:
tickers = ['AAPL', 'MSFT', 'AMZN', 'JPM', 'XOM', 'JNJ', 'WMT', 'CAT', 'NEE', 'KO',
                 'UPS', 'NVDA']
target_date = pd.Timestamp("2020-01-02")

close_prices = get_close_prices(tickers, target_date)

print(close_prices)

Ticker
AAPL     75.087502
AMZN     94.900497
CAT     150.529999
JNJ     145.970001
JPM     141.089996
KO       54.990002
MSFT    160.619995
NEE      59.654999
NVDA      5.997750
UPS     116.790001
WMT      39.646667
XOM      70.900002
Name: 2020-01-02 00:00:00, dtype: float64

**Calculating number of each position**

In [ ]:
weights = initial_capital/(len(tickers) * close_prices)
weights

Ticker
AAPL     110.981630
AMZN      87.811271
CAT       55.359951
JNJ       57.089356
JPM       59.063956
KO       151.542700
MSFT      51.882291
NEE      139.692121
NVDA    1389.409963
UPS       71.353140
WMT      210.190007
XOM      117.536434
Name: 2020-01-02 00:00:00, dtype: float64

**Calculating capital in a quarter**

In [ ]:
target_date = pd.Timestamp("2020-04-01")

close_prices = get_close_prices(tickers, target_date)

capital = sum(close_prices * weights)
capital

82757.5946734973

## The work cycle for 2 years

In [ ]:
initial_capital = 100_000
capital = initial_capital
tickers = ['AAPL', 'MSFT', 'AMZN', 'JPM', 'XOM', 'JNJ', 'WMT', 'CAT', 'NEE', 'KO',
                 'UPS', 'NVDA']
start_date = pd.Timestamp("2020-01-02")

for months in range(0, 25, 3):
    # forming pd.Series of stock prices
    target_date = start_date + pd.DateOffset(months=months)
    print(f"\nПлановая дата: {target_date.date()}")
    close_prices = get_close_prices(tickers, target_date)
    print(close_prices)
    print()

    # recalculating portfolio capital
    if months > 0:
        capital = sum(close_prices * weights)
        print(capital)
    else:
        print(initial_capital)
    print()

    # forming number of portfolio positions
    weights = capital/(len(tickers) * close_prices)
    print(weights)
    print()

print(initial_capital, capital, sep=',')

Плановая дата: 2020-01-02
Ticker
AAPL     72.271500
AMZN     94.900497
CAT     132.067871
JNJ     121.338524
JPM     117.899216
KO       45.141266
MSFT    151.544266
NEE      50.335987
NVDA      5.963803
UPS      87.781105
WMT      36.203281
XOM      52.606407
Name: 2020-01-02 00:00:00, dtype: float64

100000

Ticker
AAPL     115.305942
AMZN      87.811271
CAT       63.098869
JNJ       68.678381
JPM       70.681839
KO       184.605663
MSFT      54.989434
NEE      165.554185
NVDA    1397.318611
UPS       94.933110
WMT      230.181713
XOM      158.409095
Name: 2020-01-02 00:00:00, dtype: float64


Плановая дата: 2020-04-02
Ticker
AAPL     59.076008
AMZN     95.941498
CAT     103.140572
JNJ     111.387589
JPM      73.595543
KO       36.394947
MSFT    146.887283
NEE      48.018242
NVDA      6.354400
UPS      70.623169
WMT      36.274815
XOM      30.406351
Name: 2020-04-02 00:00:00, dtype: float64

86092.02353877752

Ticker
AAPL     121.442453
AMZN      74.778229
CAT       69.558809
JNJ       64.408750
JPM       97.483285
KO       197.124488
MSFT      48.842453
NEE      149.408538
NVDA    1129.034231
UPS      101.586142
WMT      197.777311
XOM      235.948578
Name: 2020-04-02 00:00:00, dtype: float64


Плановая дата: 2020-07-02
Ticker
AAPL     88.059410
AMZN    144.514999
CAT     113.877434
JNJ     118.746979
JPM      79.503693
KO       37.502708
MSFT    195.680389
NEE      52.536404
NVDA      9.567928
UPS      87.716827
WMT      36.606335
XOM      33.819305
Name: 2020-07-02 00:00:00, dtype: float64

104552.98256700576

Ticker
AAPL     98.941709
AMZN     60.289580
CAT      76.509878
JNJ      73.372381
JPM     109.589231
KO      232.323182
MSFT     44.525405
NEE     165.842120
NVDA    910.620174
UPS      99.328131
WMT     238.012044
XOM     257.626478
Name: 2020-07-02 00:00:00, dtype: float64


Плановая дата: 2020-10-02
Ticker
AAPL    109.531944
AMZN    156.250000
CAT     134.690414
JNJ     124.006088
JPM      83.991112
KO       41.580181
MSFT    196.086899
NEE      60.252277
NVDA     13.005908
UPS     128.878082
WMT      43.321327
XOM      25.802271
Name: 2020-10-02 00:00:00, dtype: float64

118852.07605939131

Ticker
AAPL     90.424211
AMZN     63.387774
CAT      73.534109
JNJ      79.869786
JPM     117.921283
KO      238.198570
MSFT     50.509951
NEE     164.381167
NVDA    761.526197
UPS      76.850458
WMT     228.625029
XOM     383.855348
Name: 2020-10-02 00:00:00, dtype: float64


Плановая дата: 2021-01-02
Ticker
AAPL    125.632523
AMZN    159.331497
CAT     164.623947
JNJ     133.628311
JPM     109.000534
KO       44.792767
MSFT    207.565414
NEE      63.917133
NVDA     13.060798
UPS     127.209854
WMT      45.345757
XOM      33.251328
Name: 2021-01-04 00:00:00, dtype: float64

131605.32820619163

Ticker
AAPL     87.295156
AMZN     68.832032
CAT      66.619170
JNJ      82.071760
JPM     100.615201
KO      244.841110
MSFT     52.836889
NEE     171.583269
NVDA    839.696850
UPS      86.212745
WMT     241.855281
XOM     329.824747
Name: 2021-01-04 00:00:00, dtype: float64


Плановая дата: 2021-04-02
Ticker
AAPL    122.407608
AMZN    161.336502
CAT     212.346802
JNJ     140.415680
JPM     134.778580
KO       45.208408
MSFT    238.032852
NEE      66.468727
NVDA     13.936095
UPS     134.384811
WMT      43.328705
XOM      46.038658
Name: 2021-04-05 00:00:00, dtype: float64

145024.47130542508

Ticker
AAPL     98.730568
AMZN     74.907863
CAT      56.913372
JNJ      86.068540
JPM      89.668348
KO      267.325771
MSFT     50.771868
NEE     181.820431
NVDA    867.199341
UPS      89.931090
WMT     278.923006
XOM     262.504884
Name: 2021-04-05 00:00:00, dtype: float64


Плановая дата: 2021-07-02
Ticker
AAPL    136.308716
AMZN    175.548996
CAT     198.749130
JNJ     146.089966
JPM     137.681854
KO       46.730694
MSFT    265.959167
NEE      64.644356
NVDA     20.416380
UPS     166.109909
WMT      43.711010
XOM      52.223537
Name: 2021-07-02 00:00:00, dtype: float64

159132.4584194448

Ticker
AAPL     97.286796
AMZN     75.540382
CAT      66.722497
JNJ      90.773094
JPM      96.316528
KO      283.775761
MSFT     49.861181
NEE     205.138377
NVDA    649.529361
UPS      79.832915
WMT     303.379817
XOM     253.928379
Name: 2021-07-02 00:00:00, dtype: float64


Плановая дата: 2021-10-02
Ticker
AAPL    135.713135
AMZN    159.488998
CAT     177.215332
JNJ     138.470001
JPM     147.317734
KO       46.049244
MSFT    271.708344
NEE      69.381386
NVDA     19.667454
UPS     140.849640
WMT      42.500378
XOM      51.797108
Name: 2021-10-04 00:00:00, dtype: float64

154747.36973708303

Ticker
AAPL     95.021121
AMZN     80.855822
CAT      72.768050
JNJ      93.129299
JPM      87.536061
KO      280.039650
MSFT     47.461237
NEE     185.865618
NVDA    655.682952
UPS      91.555890
WMT     303.423519
XOM     248.963981
Name: 2021-10-04 00:00:00, dtype: float64


Плановая дата: 2022-01-02
Ticker
AAPL    177.786407
AMZN    170.404495
CAT     190.991165
JNJ     150.161621
JPM     143.544907
KO       51.932365
MSFT    321.856445
NEE      80.489738
NVDA     30.026142
UPS     169.375488
WMT      45.475803
XOM      54.041130
Name: 2022-01-03 00:00:00, dtype: float64

178346.29393295632

Ticker
AAPL     83.595767
AMZN     87.217131
CAT      77.816119
JNJ      98.974632
JPM     103.536876
KO      286.183597
MSFT     46.176460
NEE     184.647030
NVDA    494.975049
UPS      87.747001
WMT     326.815362
XOM     275.016291
Name: 2022-01-03 00:00:00, dtype: float64

100000,178346.29393295632

# Creating Markowitz baseline

In [ ]:
import numpy as np
import pandas as pd
import yfinance as yf
from pypfopt import EfficientFrontier

## Formulas

**Daily return**
$$r_t = \frac{P_t}{P_{t-1}} - 1$$

In [2]:
def daily_return(close):
    return close.pct_change(fill_method=None).iloc[1:]

**Geometric mean**
$$
g=\left(\prod_{t=1}^{n}(1+r_t)\right)^{1/n}-1
$$

In [3]:
def geometric_mean(returns):
    return np.expm1(np.log1p(returns).mean(axis=0))

## Constants

In [31]:
# Length of window
L = 252
# Portfolio rebalancing frequency (days)
M = 1
# Maximum and minimum weight per asset
W_MAX = 1
W_MIN = 0.01
# Maximum portfolio volatility per year
SIGMA_MAX = 0.2

## Get close prices since 1994

In [4]:
tickers = ['AAPL', 'MSFT', 'AMZN', 'JPM', 'XOM', 'JNJ', 'WMT', 'CAT', 'NEE', 'KO',
           'UPS', 'NVDA']
start_date = "1994-01-02"
end_date = "2026-01-01"

data = yf.download(
    tickers=tickers,
    start=start_date,
    end=end_date,
    interval="1d",
    auto_adjust=False,
    group_by="column",
    progress=False,
)

if data is None or data.empty:
        raise ValueError("Не удалось получить цены.")

close = data["Adj Close"].reindex(columns=tickers)
close.index.name = "Date"
close.columns.name = None

print(close.head())

                AAPL      MSFT  AMZN       JPM       XOM       JNJ       WMT  \
Date
1994-01-03  0.217798  1.519884   NaN  5.300228  5.632161  5.131828  2.588819
1994-01-04  0.229645  1.526997   NaN  5.316640  5.676333  5.117649  2.614199
1994-01-05  0.246048  1.560193   NaN  5.267410  5.709463  5.103473  2.588819
1994-01-06  0.238758  1.605243   NaN  5.185362  5.676333  5.004238  2.499987
1994-01-07  0.241492  1.617099   NaN  5.333045  5.632161  5.060944  2.474606

                 CAT       NEE        KO  UPS  NVDA
Date
1994-01-03  5.117660  1.600976  4.916636  NaN   NaN
1994-01-04  5.210709  1.590614  4.875204  NaN   NaN
1994-01-05  5.210709  1.569890  4.750905  NaN   NaN
1994-01-06  5.239339  1.538803  4.654229  NaN   NaN
1994-01-07  5.174920  1.554346  4.709474  NaN   NaN

**There are a lot of NaN values for AMZN, UPS, and NVDA because they only went public in 1999.**

In [10]:
a = close.copy()
a = a.loc[a.index >= '1999-11-10']
a.isna().any(axis=1).sum()

np.int64(0)

**There are no NaN after 1999, then we can just drop all NaN**

In [5]:
close = close.dropna(how="any")

close.head()

,AAPL,MSFT,AMZN,JPM,XOM,JNJ,WMT,CAT,NEE,KO,UPS,NVDA
Date,,,,,,,,,,,,
1999-11-10,0.683715,26.442665,3.600000,25.085333,16.416655,25.667831,12.064291,13.814909,2.475286,13.677938,31.281332,0.054072
1999-11-11,0.689791,27.201418,3.650000,25.260475,16.592161,25.870310,12.130291,14.136185,2.488522,13.412061,34.375084,0.057883
1999-11-12,0.677640,27.068632,3.746875,26.467079,16.821676,25.924669,12.433874,14.136185,2.475286,13.589314,32.312584,0.060980
1999-11-15,0.668761,26.404726,3.675000,25.708101,16.848667,25.862206,12.447082,14.280757,2.458739,13.766565,31.625076,0.059789
1999-11-16,0.681846,26.499577,3.946875,26.778458,17.105185,26.518116,12.645062,14.602036,2.468666,14.002901,30.250072,0.065506

## Getting returns

In [6]:
returns = daily_return(close)

returns.head()

,AAPL,MSFT,AMZN,JPM,XOM,JNJ,WMT,CAT,NEE,KO,UPS,NVDA
Date,,,,,,,,,,,,
1999-11-11,0.008886,0.028694,0.013889,0.006982,0.010691,0.007888,0.005471,0.023256,0.005348,-0.019438,0.098901,0.070473
1999-11-12,-0.017615,-0.004882,0.026541,0.047766,0.013833,0.002101,0.025027,0.000000,-0.005319,0.013216,-0.060000,0.053507
1999-11-15,-0.013104,-0.024527,-0.019183,-0.028676,0.001605,-0.002409,0.001062,0.010227,-0.006685,0.013043,-0.021277,-0.019530
1999-11-16,0.019567,0.003592,0.073980,0.041635,0.015225,0.025362,0.015906,0.022497,0.004037,0.017167,-0.043478,0.095618
1999-11-17,-0.010280,-0.026486,-0.030879,-0.047965,0.013417,-0.004711,-0.016701,-0.025302,0.000000,0.011604,0.025568,0.038176

## Calculating mean and covariation matrix for $l$ dates

In [32]:
mean = returns[:L].mean()
cov_matrix = returns[:L].cov()

In [29]:
mean

AAPL   -0.001493
MSFT   -0.000370
AMZN   -0.001149
JPM    -0.000335
XOM     0.000962
JNJ    -0.000105
WMT    -0.000122
CAT    -0.001022
NEE     0.001643
KO      0.000554
UPS    -0.000122
NVDA    0.008693
dtype: float64

In [30]:
cov_matrix

,AAPL,MSFT,AMZN,JPM,XOM,JNJ,WMT,CAT,NEE,KO,UPS,NVDA
AAPL,0.002951,0.000444,0.000716,0.000249,-0.000039,-0.000021,0.000106,0.000177,-0.000094,-0.000044,0.000105,0.000808
MSFT,0.000444,0.001064,0.000541,0.000170,0.000039,0.000019,0.000102,0.000045,-0.000020,-0.000015,0.000270,0.000658
AMZN,0.000716,0.000541,0.003755,0.000367,-0.000144,-0.000214,0.000184,0.000124,-0.000088,-0.000084,0.000224,0.000991
JPM,0.000249,0.000170,0.000367,0.000801,0.000045,0.000025,0.000263,0.000237,0.000049,0.000061,0.000111,0.000114
XOM,-0.000039,0.000039,-0.000144,0.000045,0.000395,0.000081,0.000091,0.000081,0.000097,0.000104,-0.000046,-0.000024
JNJ,-0.000021,0.000019,-0.000214,0.000025,0.000081,0.000460,0.000137,0.000106,0.000051,0.000154,0.000006,-0.000150
WMT,0.000106,0.000102,0.000184,0.000263,0.000091,0.000137,0.000986,0.000258,0.000088,0.000185,0.000063,-0.000188
CAT,0.000177,0.000045,0.000124,0.000237,0.000081,0.000106,0.000258,0.000763,0.000080,0.000168,0.000116,-0.000271
NEE,-0.000094,-0.000020,-0.000088,0.000049,0.000097,0.000051,0.000088,0.000080,0.000411,0.000110,0.000014,-0.000063
KO,-0.000044,-0.000015,-0.000084,0.000061,0.000104,0.000154,0.000185,0.000168,0.000110,0.000703,-0.000044,-0.000430
UPS,0.000105,0.000270,0.000224,0.000111,-0.000046,0.000006,0.000063,0.000116,0.000014,-0.000044,0.000717,0.000143
NVDA,0.000808,0.000658,0.000991,0.000114,-0.000024,-0.000150,-0.000188,-0.000271,-0.000063,-0.000430,0.000143,0.004996

## Get Markowitz weights for 1 time period

In [33]:
ef = EfficientFrontier(mean, cov_matrix, weight_bounds=(W_MIN, W_MAX))

ef.efficient_risk(target_volatility=SIGMA_MAX / np.sqrt(252))

weights = pd.Series(ef.weights, index=mean.index, name='weights')
weights

AAPL    0.010000
MSFT    0.010000
AMZN    0.010000
JPM     0.010000
XOM     0.215062
JNJ     0.100026
WMT     0.010000
CAT     0.010000
NEE     0.301213
KO      0.123319
UPS     0.096605
NVDA    0.103773
Name: weights, dtype: float64

## Cycle for 2 years

In [44]:
# 2 years of 252 trading days
years = 2
days = 252 * years

first_day = L
last_day = L + days

initial_capital = 100_000

**Portfolio for first day**

In [45]:
# calculating wheigts
mean = returns[first_day - L:first_day].mean()
cov_matrix = returns[first_day - L:first_day].cov()

ef = EfficientFrontier(mean, cov_matrix, weight_bounds=(W_MIN, W_MAX))
ef.efficient_risk(target_volatility=SIGMA_MAX / np.sqrt(252))
weights = pd.Series(ef.weights, index=mean.index, name='weights')

# buying assets
money_in_each_asset = weights * initial_capital
number_of_shares = money_in_each_asset / close.iloc[first_day]

In [46]:
for day in range(first_day + 1, last_day):
    # calculating capital for next day
    money_in_each_asset = number_of_shares * close.iloc[day]
    capital = sum(money_in_each_asset)

    # calculating mean and covariation matrix over the last 252 days before 'day'
    mean = returns[day - L:day].mean()
    cov_matrix = returns[day - L:day].cov()

    # calculating portfolio weights for 'day'
    ef = EfficientFrontier(mean, cov_matrix, weight_bounds=(W_MIN, W_MAX))
    ef.efficient_risk(target_volatility=SIGMA_MAX / np.sqrt(252))
    weights = pd.Series(ef.weights, index=mean.index, name='weights')

    money_in_each_asset = weights * capital
    number_of_shares = money_in_each_asset / close.iloc[day]

In [48]:
money_in_each_asset = number_of_shares * close.iloc[last_day]
capital = sum(money_in_each_asset)
capital

84010.38689249897

**CAGR**

In [49]:
CAGR = (capital / initial_capital) ** (1 / years) - 1
CAGR

-0.08342819761625353