# Imports

In [ ]:
import sys
from pathlib import Path

import pandas as pd

from src.extract_risk_factors import LocalFiling

In [ ]:
# Если текущая рабочая папка — notebooks
project_root = Path.cwd().parent.parent
sys.path.insert(0, str(project_root))

# first 10-Q 'not_found'

In [ ]:
file_path = '../../data/raw/10-Q/AAPL/0001104659-06-005910.txt'

In [18]:
filing = LocalFiling.from_sgml(file_path)
filing.view()

UNITED STATES

SECURITIES AND EXCHANGE
COMMISSION

Washington,
D.C. 20549

Form 10-Q

(Mark One)

  ý       QUARTERLY
          REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE
          ACT OF 1934
 ─────────────────────────────────────────────────────────────────────────────

For the
quarterly period ended December 31, 2005

or

  TRANSITION
  REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE
  ACT OF 1934
 ─────────────────────────────────────────────────────────────────────

For the
transition period from
to.

Commission
file number: 000-10030

APPLE COMPUTER, INC.

(Exact name of Registrant as
specified in its charter)

  CALIFORNIA                             942404110
 ───────────────────────────────────────────────────────────────────────
  (State or                              (I.R.S.
  other jurisdiction                     Employer Identification No.)


  of incorporation or organization)
  1                                      95014
  Infinite Loop


  Cupertino, California
  (Address of                            (Zip Code)
  principal executive offices)

Registrant’s telephone number,
including area code: (408) 996-1010

Indicate by check mark whether the registrant (1) has filed all
reports required to be filed by Section 13 or 15(d) of the Securities
Exchange Act of 1934 during the preceding 12 months (or for such shorter period
that the registrant was required to file such reports), and (2) has been
subject to such filing requirements for the past 90 days.

Yes ý No o

Indicate by check mark whether the registrant is a large accelerated
filer, an accelerated filer, or a non-accelerated filer. See definition of “accelerated filer and
large accelerated filer” in Rule 12b-2 of the Exchange Act.

Large accelerated filer ý Accelerated
filer o Non-accelerated
filer o

Indicate by check mark whether the registrant is a shell company (as
defined in Rule 12b-2 of the Exchange Act).

Yes o No ý

848,612,359 shares of common
stock issued and outstanding as of January 25, 2006

PART I. FINANCIAL INFORMATION

Item 1. Financial Statements

APPLE COMPUTER, INC.

CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS
(Unaudited)

(in millions, except share and
per share amounts)

                                                                                     Three Months Ended
                                                                                     December 31, 2005
December 25, 2004
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────
  Net sales                                                                          $
5,749      $                        3,490
  Cost of
4,185                               2,494
  sales (including stock-based compensation expense of $5 and $0, respectively)
  Gross margin
1,564      996
  Operating
  expenses:
  Research and                                                                       182
123
  development (including stock-based compensation expense of $15 and $2,
  respectively)
  Selling,                                                                           632
470
  general, and administrative (including stock-based compensation expense of
  $24 and $8, respectively)
  Total                                                                              814
593
  operating expenses
  Operating                                                                          750
403
  income
  Other income                                                                       81
26
  and expense
  Income                                                                             831
429
  before provision for income taxes
  Provision                                                                          266
134
  for income taxes
  Net income                                                                         $
565      $                          295
  Earnings per
  common share:
  Basic                                                                              $
0.68      $                         0.37
  Diluted                                                                            $
0.65      $                         0.35
  Shares used
  in computing earnings per share (in thousands):
  Basic
830,781                             789,032
  Diluted
874,207                             838,174

See accompanying notes to condensed consolidated
financial statements.

APPLE COMPUTER, INC.

CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)

(in millions, except share amounts)

                                                                             December 31, 2005
September 24, 2005
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────
  ASSETS:
  Current
  assets:
  Cash and                                                                   $                       4,150      $
3,491
  cash equivalents
  Short-term                                                                                         4,557
4,770
  investments
  Accounts                                                                                           1,331      895
  receivable, less allowances of $50 and $46, respectively
  Inventories                                                                244                                165
  Deferred tax                                                               471                                331
  assets
  Other                                                                                              1,409      648
  current assets
  Total                                                                                             12,162
10,300
  current assets
  Property, plant                                                            855                                817
  and equipment, net
  Goodwill                                                                   69                                 69
  Acquired                                                                   24                                 27
  intangible assets
  Other assets                                                                                       1,071      338
  Total assets                                                               $                      14,181      $
11,551
  LIABILITIES
  AND SHAREHOLDERS’ EQUITY:
  Current
  liabilities:
  Accounts                                                                   $                       2,896      $
1,779
  payable
  Accrued                                                                                            2,164
1,705
  expenses
  Total                                                                                              5,060
3,484
  current liabilities
  Non-current                                                                741                                601
  liabilities
  Total                                                                                              5,801
4,085
  liabilities
  Commitments
  and contingencies
  Shareholders’
  equity:
  Common                                                                                             3,815
3,521
  stock, no par value; 1,800,000,000 shares authorized; 845,617,174 and
  835,019,364 shares issued and outstanding, respectively
  Deferred                                                                   —                                  (60
  stock compensation
  Retained                                                                                           4,570
4,005
  earnings
  Accumulated                                                                (5                                 —
  other comprehensive income (loss)
  Total                                                                                              8,380
7,466
  shareholders’ equity
  Total                                                                      $                      14,181      $
11,551
  liabilities and shareholders’ equity

See accompanying notes to
condensed consolidated financial statements.

APPLE COMPUTER, INC.

CONDENSED CONSOLIDATED
STATEMENTS OF CASH FLOWS (Unaudited)

(in millions)

                                                                     Three
                                                              Months Ended
                                                         December 31, 2005                  December 25, 2004
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─────────
  Cash and                                                               $       3,491                      $
2,969
  cash equivalents, beginning of the period
  Operating
  Activities:
  Net income                                                           565                                295
  Adjustments to reconcile net income to cash
  generated by operating activities:
  Depreciation, amortization, and accretion                             52                                 41
  Stock-based compensation expense                                      44                                 10
  Provision for (benefit from) deferred                                 70                                 (8
  income taxes
  Excess tax benefits from stock options                                 —                                140
  Loss on disposition of property, plant, and                            —                                  2
  equipment
  Changes in operating assets and
  liabilities:
  Accounts receivable                                                 (436                                (91
  Inventories                                                          (79                                (55
  Other current assets                                                (757                                (87
  Other assets                                                        (771                                (27
  Accounts payable                                                               1,117                    286
  Other liabilities                                                    478                                269
  Cash generated by operating activities                               283                                775
  Investing
  Activities:
  Purchases of short-term investments                                           (3,185
(2,393
  Proceeds from maturities of short-term                                         3,396                    777
  investments
  Proceeds from sales of short-term                                      —                                138
  investments
  Purchases of property, plant, and equipment                          (82                                (58
  Other                                                                (36                                 13
  Cash generated by (used for) investing                                93
(1,523
  activities
  Financing
  Activities:
  Proceeds from issuance of common stock                               134                                254
  Excess tax benefits from stock-based compensation                    149                                  —
  Cash generated by financing activities                               283                                254
  Increase                                                             659                               (494
  (decrease) in cash and cash equivalents
  Cash and                                                               $       4,150                      $
2,475
  cash equivalents, end of the period
  Supplemental
  cash flow disclosures:
  Cash paid for income taxes, net                                        $          22                      $
37

See accompanying notes to
condensed consolidated financial statements.

APPLE COMPUTER, INC.

Notes to Condensed Consolidated Financial Statements
(Unaudited)

Note 1 - Summary of Significant Accounting
Policies

Apple Computer, Inc. and its subsidiaries (the
Company) designs, manufactures, and markets personal computers and related
software, services, peripherals, and networking solutions. The Company also designs, develops, and
markets a line of portable digital music players along with related accessories
and services including the online distribution of third-party music, audio
books, music videos, short films, and television shows. The Company sells its products worldwide
through its online stores, its own retail stores, its direct sales force, and
third-party wholesalers, resellers, and value-added resellers. In addition to its own hardware, software, and
peripheral products, the Company sells a variety of third-party hardware and
software products through its online and retail stores. The Company sells to education, consumer,
creative professional, business, and government customers.

Basis
of Presentation and Preparation

The accompanying condensed
consolidated financial statements include the accounts of the Company. Intercompany accounts and transactions have
been eliminated. The preparation of these condensed consolidated financial
statements in conformity with U.S. generally accepted accounting principles
requires management to make estimates and assumptions that affect the amounts
reported in these condensed consolidated financial statements and accompanying
notes. Actual results could differ materially from those estimates. Certain prior
year amounts in the consolidated financial statements and notes thereto have
been reclassified to conform to the current year presentation.

These condensed consolidated financial statements and
accompanying notes should be read in conjunction with the Company’s annual
consolidated financial statements and the notes thereto for the fiscal year
ended September 24, 2005, included in its Annual Report on Form 10-K
for the year ended September 24, 2005 (the 2005 Form 10-K).

The Company’s fiscal year is the 52 or 53-week period
that ends on the last Saturday of September. The Company’s first quarter of
fiscal year 2006 contained 14 weeks and the first quarter of its fiscal year
2005 contained 13 weeks. The Company’s fiscal year 2006 will end on September 30,
2006 and include 53 weeks while fiscal year 2005 included 52 weeks. Unless
otherwise stated, references to particular years or quarters refer to the
Company’s fiscal years ended in September and the associated quarters of
those fiscal years.

Common
Stock Split

On February 28, 2005, the
Company effected a two-for-one stock split to shareholders of record as of February 18,
2005. All share and per share
information has been retroactively adjusted to reflect the stock split.

Software
Development Costs

Research and development costs are expensed as incurred. Development
costs of computer software to be sold, leased, or otherwise marketed are
subject to capitalization beginning when a product’s technological feasibility
has been established and ending when a product is available for general release
to customers pursuant to Statement of Financial Accounting Standards (SFAS) No. 86, Computer Software to be Sold,
Leased, or Otherwise
Marketed. In most instances, the Company’s products are released
soon after technological feasibility has been established. Therefore, costs
incurred subsequent to achievement of technological feasibility are usually not
significant, and generally all software development costs have been expensed.

In the fourth quarter of 2004, the Company began
incurring substantial development costs associated with Mac OS X version 10.4
Tiger subsequent to achievement of technological feasibility as evidenced by
public demonstration in August 2004 and the subsequent release of a
developer beta version of the product. During the first quarter of 2005, the
Company capitalized approximately $14.8 million of costs associated with the
development of Tiger. In accordance with
SFAS No. 86, amortization of this asset to cost of sales began in April 2005
when the Company began shipping Tiger and is being recognized on a
straight-line basis over a three-year estimated useful life.

Stock-Based
Compensation

On September 25, 2005, the Company adopted SFAS No. 123
(revised 2004) (SFAS No. 123R), Share-Based Payment,
which addresses the accounting for stock-based payment transactions in which an
enterprise receives

employee services in exchange for (a) equity instruments of the
enterprise or (b) liabilities that are based on the fair value of the
enterprise’s equity instruments or that may be settled by the issuance of such
equity instruments. In January 2005, the Securities and Exchange
Commission (SEC) issued Staff Accounting Bulletin (SAB) No. 107,
which provides supplemental implementation guidance for SFAS No. 123R.
SFAS No. 123R eliminates the ability to account for stock-based
compensation transactions using the intrinsic value method under Accounting
Principles Board (APB) Opinion No. 25, Accounting for Stock
Issued to Employees, and instead generally require that such
transactions be accounted for using a fair-value-based method. The Company uses the Black-Scholes-Merton (“BSM”)
option-pricing model to determine the fair-value of stock-based awards under
SFAS No. 123R, consistent with that used for pro forma disclosures under
SFAS No. 123, Accounting for Stock-Based
Compensation. The Company has elected the modified prospective
transition method as permitted by SFAS No. 123R and accordingly prior
periods have not been restated to reflect the impact of SFAS No. 123R. The modified prospective transition method
requires that stock-based compensation expense be recorded for all new and
unvested stock options, restricted stock, restricted stock units, and employee
stock purchase plan shares that are ultimately expected to vest as the
requisite service is rendered beginning on September 25, 2005, the first
day of the Company’s fiscal year 2006. Stock-based compensation expense for
awards granted prior to September 25, 2005 is based on the grant date
fair-value as determined under the pro forma provisions of SFAS No. 123. The Company has recorded an incremental
$32
million of stock-based compensation expense during the first quarter of 2006 as
a result of the adoption of SFAS No. 123R. In
accordance with SFAS No. 123R, beginning in the first quarter of 2006 the
Company has presented excess tax benefits from the exercise of stock-based
compensation awards as a financing activity in the Condensed Consolidated
Statement of Cash Flows.

No stock-based compensation
costs were capitalized as part of the cost of an asset as of December 31,
2005. The income tax benefit related to
stock-based compensation expense was $14 million for the quarter ended December 31,
2005. As of December 31, 2005, $398 million of total unrecognized
compensation cost related to stock options and restricted stock units are
expected to be recognized over a weighted-average period of 2 years.

Prior to the adoption of SFAS No. 123R, the
Company measured compensation expense for its employee stock-based compensation
plans using the intrinsic value method prescribed by APB Opinion No. 25.
The Company applied the disclosure provisions of SFAS No. 123 as amended
by SFAS No. 148, Accounting for Stock-Based
Compensation - Transition and Disclosure as if the fair-value-based
method had been applied in measuring compensation expense. Under APB Opinion No. 25,
when the exercise price of the Company’s employee stock options was equal to
the market price of the underlying stock on the date of the grant, no
compensation expense was recognized.

The following table illustrates the effect on net income after taxes

# first 10-K 'not_found'

In [ ]:
file_path = '../../data/raw/10-K/AAPL/0001104659-05-058421.txt'

In [24]:
filing = LocalFiling.from_sgml(file_path)
filing.view()

UNITED STATES

SECURITIES AND EXCHANGE COMMISSION

Washington,
D.C. 20549

Form 10-K

(Mark One)

x ANNUAL
REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT
OF 1934

For the fiscal year ended
September 24, 2005

or

o TRANSITION
REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT
OF 1934

For the transition period from to

Commission file number 0-10030

APPLE COMPUTER, INC.

(Exact name of registrant
as specified in its charter)

  CALIFORNIA                             942404110
 ──────────────────────────────────────────────────────────────
  (State or other                        (I.R.S. Employer
  jurisdiction

                                         Identification No.)
  of incorporation or organization)
  1 Infinite Loop                        95014


  Cupertino, California
  (Address of                            (Zip Code)
  principal executive offices)

Registrant’s telephone
number, including area code: (408) 996-1010

Securities registered
pursuant to Section 12(b) of the Act: None

Securities registered
pursuant to Section 12(g) of the Act: Common Stock, no par value (Titles of classes)

Indicate by check mark
whether the registrant (1) has filed all reports required to be filed by Section 13
or 15(d) of the Securities Exchange Act of 1934 during the preceding 12
months (or for such shorter period that the registrant was required to file
such reports), and (2) has been subject to such filing requirements for
the past 90 days. Yes x No o

Indicate by check mark if
disclosure of delinquent filers pursuant to Item 405 of Regulation S-K
(section 229.405 of this chapter) is not contained herein, and will
not be contained, to the best of the registrant’s knowledge, in definitive
proxy or information statements incorporated by reference in Part III of
this Form 10-K or any amendment to this Form 10-K. x

Indicate by check mark
whether the registrant is an accelerated filer (as defined in Rule 12b-2
of the Act). Yes x No o

Indicate by check mark
whether the registrant is a shell company (as defined in Rule 12b-2 of the
Act). Yes o No x

The aggregate market value
of the voting and non-voting stock held by non-affiliates of the registrant, as
of March 26, 2005, was approximately $29,434,521,480 based upon the
closing price reported for such date on the NASDAQ National Market. For
purposes of this disclosure, shares of Common Stock held by persons who hold
more than 5% of the outstanding shares of Common Stock and shares held by
executive officers and directors of the registrant have been excluded because
such persons may be deemed to be affiliates. This determination of executive
officer or affiliate status is not necessarily a conclusive determination for
other purposes.

842,767,948 shares of Common Stock Issued and
Outstanding as of November 18, 2005

PART I

The Business section and other parts of this Annual
Report on Form 10-K (“Form 10-K”) contain forward-looking
statements that involve risks and uncertainties. Many of the forward-looking
statements are located in “Management’s Discussion and Analysis of Financial
Condition and Results of Operations.” Forward-looking statements can also be
identified by words such as “anticipates,” “expects,” “believes,” “plans,” “predicts,”
and similar terms. Forward-looking statements are not guarantees of future performance
and the Company’s actual results may differ significantly from the results
discussed in the forward-looking statements. Factors that might cause
such differences include, but are not limited to, those discussed in the
subsection entitled “Factors That May Affect Future Results and Financial
Condition” under Part II, Item 7 of this Form 10-K. The Company
assumes no obligation to revise or update any forward-looking statements for
any reason, except as required by law.

Item 1. Business

Company Background

Apple Computer, Inc.
(“Apple” or the “Company”) was incorporated under the laws of the State of
California on January 3, 1977. The Company designs, manufactures, and
markets personal computers and related software, services, peripherals, and
networking solutions. The Company also designs, develops, and markets a line of
portable digital music players along with related accessories and services
including the online distribution of third-party music, audio books, music
videos, short films, and television shows. The Company’s products and services
include the Macintosh line of desktop and notebook computers, the iPod digital
music player, the Xserve G5 server and Xserve RAID storage products, a
portfolio of consumer and professional software applications, the Mac OS X
operating system, the iTunes Music Store, a portfolio of peripherals that
support and enhance the Macintosh and iPod product lines, and a variety of
other service and support offerings. The Company sells its products worldwide
through its online stores, its own retail stores, its direct sales force, and
third-party wholesalers, resellers, and value added resellers. The Company also
sells a variety of third-party products that are compatible with the Company’s
Macintosh and iPod product lines, including computer printers and printing
supplies, storage devices, computer memory, digital camcorders and still
cameras, personal digital assistants, iPod accessories, and various other
computing products and supplies through its online and retail stores. The
Company’s fiscal year ends on the last Saturday of September. Unless otherwise
stated, all information presented in this Form 10-K is based on the
Company’s fiscal calendar.

Business Strategy

The Company is committed
to bringing the best personal computing and music experience to students,
educators, creative professionals, businesses, government agencies, and
consumers through its innovative hardware, software, peripherals, services, and
Internet offerings. The Company’s business strategy leverages its unique
ability, through the design and development of its own operating system,
hardware, and many software applications and technologies, to bring to its
customers new products and solutions with superior ease-of-use, seamless
integration, and innovative industrial design. The Company believes continual
investment in research and development is critical to facilitate innovation of
new and improved products and technologies. Besides updates to its existing
line of personal computers and related software, services, peripherals, and
networking solutions, the Company continues to capitalize on the convergence of
digital consumer electronics and the computer by creating innovations like the
iPod and iTunes Music Store. The Company’s strategy also includes expanding its
distribution network to effectively reach more of its targeted customers and
provide them a high-quality sales and after-sales support experience.

Digital Hub

The Company believes personal computing is in an era
in which the personal computer functions for both professionals and consumers
as the digital hub for advanced new digital devices such as the Company’s

iPod digital music players, personal digital
assistants, cellular phones, digital camcorders and still cameras, CD and DVD
players, televisions, and other consumer electronic devices. The attributes of
the personal computer include a high quality user interface, relatively
inexpensive data storage, and the ability to run complex applications and
easily connect to the Internet. Apple is the only company in the personal
computer industry that controls the design and development of the entire
personal computer - from the hardware and operating system to sophisticated
applications. Additionally, the Company’s products provide innovative
industrial design, intuitive ease-of-use, and built-in networking,
graphics and multimedia capabilities. Thus, the Company is uniquely positioned
to offer integrated digital hub products and solutions.

The Company develops
products and technologies that adhere to many industry standards in order to
provide an optimized user experience through interoperability with peripherals
and devices from other companies. The Company has played a role in the
development, enhancement, promotion, and/or use of numerous of these industry
standards.

Expanded
Distribution

The Company believes that a high quality buying
experience with knowledgeable salespersons who can convey the value of the
Company’s products and services is critical to attracting and retaining
customers. The Company sells many of its products and resells certain
third-party products in most of its major markets directly to consumers,
education customers, and businesses through its retail and online stores in the
U.S. and internationally. The Company has also invested in programs to enhance
reseller sales, including the Apple Sales Consultant Program, which consists of
the deployment of Apple employees and contractors to selected third-party
reseller locations. The Company believes providing direct contact with its targeted
customers is an efficient way to demonstrate the advantages of its Macintosh
computer and other products over those of its competitors. The Company has
significantly increased the points of distribution for the iPod product family
in order to make its products available at locations where its customers shop.

From inception of the retail initiative in 2001
through 2005, the Company had opened 116 retail stores in the U.S. and 8
international stores in Canada, Japan, and the U.K. The Company opened 2 additional
stores in October 2005. The Company
has typically located its stores at high traffic locations in quality shopping
malls and urban shopping districts.

One of the goals of the retail initiative is to bring new customers to
the Company and expand its installed base through sales to computer users who
currently do not own a Macintosh computer and first time personal computer
buyers. By operating its own stores and building them in desirable high traffic
locations, the Company is able to better control the customer retail experience
and attract new customers. The stores are designed to simplify and enhance the
presentation and marketing of personal computing products. To that end, retail
store configurations have evolved into various sizes in order to accommodate
market demands. The stores employ experienced and knowledgeable personnel who
provide product advice and certain hardware support services. The stores offer
a wide selection of third-party hardware, software, and various other computing
products and supplies selected to complement the Company’s own products. Additionally,
the stores provide a forum in which the Company is able to present computing
solutions to users in areas such as digital photography, digital video, music,
children’s software, and home and small business computing.

Education

For more than 25 years,
the Company has focused on the use of technology in education and has been
committed to delivering tools to help educators teach and students learn. The
Company believes effective integration of technology into classroom instruction
can result in higher levels of student achievement, especially when used to
support collaboration, information access, and the expression and
representation

of student thought and
ideas. The Company creates solutions that enable new modes of curriculum
delivery, better ways of conducting research, and opportunities for
professional development of faculty, students, and staff. The Company has
designed a range of products and services to help schools maximize their
investments in technology. This is manifested in many of the Company’s products
and services that are designed to meet the needs of education customers. These
products and services include the eMac™, iMac™, and the iBook®, video creation
and editing solutions, wireless networking, student information systems, high-quality curriculum and professional
development solutions, and one-to-one (1:1) learning solutions (primarily in
K-12). 1:1 learning solutions typically
consist of iBook portable computers for every student and teacher along with a
wireless network connected to a central server.

Creative
Professionals

Creative professionals constitute one of the Company’s
most important markets for both hardware and software products. This market is
also important to many third-party developers who provide Macintosh-compatible
hardware and software solutions. Creative customers utilize the Company’s
products for a variety of creative activities including digital video and film
production and editing; digital video and film special effects, compositing,
and titling; digital still photography and workflow management; graphic design,
publishing, and print production; music creation and production; audio
production and sound design; and web design, development, and administration.

The Company designs its
high-end hardware solutions, including servers, desktops, and portable
Macintosh systems, to incorporate the power, expandability, and features
desired by creative professionals. The Company’s operating system, Mac OS X,
incorporates powerful graphics and audio technologies and features developer
tools to optimize system and application performance when running powerful
creative solutions provided by the Company or third-party developers. The
Company also offers various software solutions to meet the needs of its
creative customers.

Business Organization

The Company manages its
business primarily on a geographic basis. The Company’s reportable operating
segments are comprised of the Americas, Europe, Japan, and Retail. The
Americas, Europe, and Japan reportable segments do not include activities
related to the Retail segment. The Americas segment includes both North and
South America. The Europe segment includes European countries as well as the
Middle East and Africa. The Retail segment currently operates Apple-owned
retail stores in the U.S., Canada, Japan, and the U.K. Other operating segments
include Asia-Pacific, which includes Australia and Asia except for Japan, and
the Company’s subsidiary, FileMaker, Inc. Each reportable geographic
operating segment provides similar hardware and software products and similar
services. Further information regarding the Company’s operating segments may be
found in Part II, Item 7 of this Form 10-K under the heading “Segment
Operating Performance,” and in Part II, Item 8 of this Form 10-K
in the Notes to Consolidated Financial Statements at Note 11, “Segment
Information and Geographic Data.”

Hardware Products

The Company offers a range
of personal computing products including desktop and notebook computers, server
and storage products, related devices and peripherals, and various third-party
hardware products. The Company’s entire line of Macintosh® systems, excluding
servers and storage systems, features the Company’s Mac OS® X Version 10.4
Tiger™ and iLife® suite of software for digital photography, music, movies, and
music creation.

Macintosh®
Computers

In June 2005, the
Company announced its plan to begin using Intel microprocessors in its
Macintosh computers. The Company plans to begin shipping certain models with
Intel microprocessors by June 2006

and to complete the
transition of all of its Macintosh computers to Intel microprocessors by the
end of calendar year 2007. The Company also announced its new translation
technology, Rosetta™, which will allow most PowerPC-based Macintosh
applications to run on new Intel-based Macintosh computers. There are potential risks and uncertainties
associated with this transition, which are further discussed in Part II,
Item 7 of this 10-K under the heading “Factors That May Affect Future
Results and Financial Condition.”

Power Mac®

The Power Mac line of
desktop personal computers is targeted at business and professional users and
is designed to meet the speed, expansion, and networking needs of the most
demanding Macintosh user. Powered by the PowerPC G5 processor, the Power Mac G5
utilizes 64-bit processing technology for memory expansion up to 16GB and
advanced 64-bit computation while also running existing 32-bit applications
natively. In October 2005, the Company updated the Power Mac G5 product
line, which now comes in three processor configurations - dual 2.0GHz, dual
2.3GHz, and a quad 2.5GHz that features two 2.5GHz dual processors. All Power
Mac G5 desktops feature a SuperDrive™ and a NVIDIA GeForce 6600 graphics card.
In addition, all Power Mac G5 desktops deliver connectivity and
high-performance input/output (I/O), including dual Gigabit Ethernet, FireWire®
800 and FireWire 400 ports, USB 2.0 ports, optical digital I/O, PCI Express
expansion, and optional AirPort® Extreme wireless networking and Bluetooth
connectivity. The new Power Mac G5 product line also includes Mighty Mouse, the
Company’s next generation mouse, featuring up to four programmable buttons and
a Scroll Ball that lets users scroll vertically, horizontally, and diagonally.

Xserve® and Xserve
RAID Storage System

Xserve is a rack-mount
server product designed for simple setup and remote management of intensive I/O
applications such as digital video, high-resolution digital imagery, and large
databases. In January 2005, the Company upgraded Xserve G5, which is now
available with either a single 2.0GHz or dual 2.3GHz PowerPC G5 processor.
Xserve G5 includes a system controller with up to 16GB of PC3200 error
correcting code memory; three hot-plug Serial ATA drive modules that deliver up
to 1.5TB of storage; and dual on-board Gigabit Ethernet for high-performance
networking. The Company’s Xserve RAID storage system was updated in September 2005
to deliver up to 7 terabytes of storage capacity and also expanded support for
heterogeneous environments. The dual independent RAID controllers with 512MB
cache per controller offer sustained throughput of over 385 Mbps - high enough to
support media production environments using
protected RAID level 5.

iMac®

The iMac line of desktop
computers is targeted at consumer and education markets. In
October 2005, the Company introduced the new iMac G5, featuring the
PowerPC G5 processor, a built-in iSight™ video camera, and a design that
integrates the entire computer into either a 17-inch or 20-inch widescreen LCD
flat-panel display. The 17-inch and 20-inch models come with 1.9GHz and 2.1GHz
PowerPC G5 Processors, respectively. The iMac G5 offers 512MB of 533MHz DDR2
memory expandable to 2.5GB and 7200 rpm Serial ATA drives expandable up to
500GB. The iMac G5 comes standard with ATI Radeon X600 Pro or XT graphics,
video memory, a SuperDrive, built-in Airport Extreme wireless networking, an
internal Bluetooth module, built-in stereo speakers and microphone, and Mighty
Mouse. The iMac G5 also offers built-in Ethernet (10/100/1000BASE-T), three USB
2.0 and two FireWire 400 ports. The iMac G5 also features Front Row media
experience with the Apple Remote, which allows users to play music and view
photos and videos via a remote control.

eMac™

The eMac, a desktop
personal computer targeted at the Company’s education customers, features a
PowerPC G4 processor, a high resolution 17-inch flat cathode ray tube display,
and preserves the all-in-one

compact design of the
original iMac. The eMac offers PowerPC G4 processors running at up to 1.42GHz,
333MHz DDR memory, an optional SuperDrive, built-in modem and Ethernet
(10/100BASE-T), ATI Radeon graphics, AirPort Extreme-ready, and USB 2.0 and 1.1
ports for connectivity to peripherals.

Mac® mini

In January 2005, the
Company introduced Mac mini, a desktop personal computer with a starting price
of $499 and weighing as little as 2.9 pounds. In July 2005, the Company
updated its Mac mini lineup, expanding to three models and increasing memory to
512MB. The first model includes a 1.25GHz PowerPC G4 processor, a 40GB hard
drive, and a Combo drive. The second model includes a 1.42GHz PowerPC G4

# Getting all 10-K not_found risk factors

In [16]:
project_dir = Path.cwd().parent.parent
indexes_path = project_dir / 'data' / 'indexes' / 'extraction' / 'AAPL.csv'
extracitons = pd.read_csv(indexes_path, dtype=str, keep_default_na=False)

In [17]:
extracitons.head()

,accession_number,form,filing_date,status,error,extraction_status,extraction_error
0,0000320193-26-000020,10-Q,2026-07-31,downloaded,,extracted,
1,0000320193-26-000013,10-Q,2026-05-01,downloaded,,extracted,
2,0000320193-26-000006,10-Q,2026-01-30,downloaded,,extracted,
3,0000320193-25-000079,10-K,2025-10-31,downloaded,,extracted,
4,0000320193-25-000073,10-Q,2025-08-01,downloaded,,extracted,

In [20]:
tenk_not_found = extracitons.loc[
    ~(
        extracitons["form"].eq("10-Q")
        | extracitons["extraction_status"].eq("extracted")
    )
].copy()
tenk_not_found

,accession_number,form,filing_date,status,error,extraction_status,extraction_error
83,0001104659-05-058421,10-K,2005-12-01,downloaded,,not_found,
87,0001047469-04-035975,10-K,2004-12-03,downloaded,,not_found,
91,0001047469-03-041604,10-K,2003-12-19,downloaded,,not_found,
95,0001047469-02-007674,10-K,2002-12-19,downloaded,,not_found,
99,0000912057-01-544436,10-K405,2001-12-21,downloaded,,not_found,
103,0000912057-00-053623,10-K,2000-12-14,downloaded,,not_found,
107,0000912057-99-010244,10-K,1999-12-22,downloaded,,error,"expected string or bytes-like object, got 'Non..."
111,0001047469-98-044981,10-K405,1998-12-23,downloaded,,error,"expected string or bytes-like object, got 'Non..."
115,0001047469-97-006960,10-K,1997-12-05,downloaded,,error,"expected string or bytes-like object, got 'Non..."
119,0000320193-96-000023,10-K,1996-12-19,downloaded,,error,"expected string or bytes-like object, got 'Non..."
123,0000320193-95-000016,10-K,1995-12-19,downloaded,,error,"expected string or bytes-like object, got 'Non..."
127,0000320193-94-000016,10-K,1994-12-13,downloaded,,error,"expected string or bytes-like object, got 'Non..."