In [3]:
from pathlib import Path

import pandas as pd

Finding if there was extraction fails in filings since start of 2006

# Only for AAPL

In [ ]:
project_dir = Path.cwd().parent.parent
indexes_path = project_dir / 'data' / 'indexes' / 'extraction'
aapl_index = indexes_path / 'AAPL.csv'
extractions = pd.read_csv(aapl_index, dtype=str, keep_default_na=False)
extractions

,accession_number,form,filing_date,period_ended,status,error,extraction_status,extraction_error
0,0000320193-26-000020,10-Q,2026-07-31,2026-06-27,downloaded,,extracted,
1,0000320193-26-000013,10-Q,2026-05-01,2026-03-28,downloaded,,extracted,
2,0000320193-26-000006,10-Q,2026-01-30,2025-12-27,downloaded,,extracted,
3,0000320193-25-000079,10-K,2025-10-31,2025-09-27,downloaded,,extracted,
4,0000320193-25-000073,10-Q,2025-08-01,2025-06-28,downloaded,,extracted,
...,...,...,...,...,...,...,...,...
125,0000320193-95-000008,10-Q,1995-05-15,1995-03-31,downloaded,,not_found,
126,0000320193-95-000003,10-Q,1995-02-09,1994-12-30,downloaded,,not_found,
127,0000320193-94-000016,10-K,1994-12-13,1994-09-30,downloaded,,error,"expected string or bytes-like object, got 'Non..."
128,0000320193-94-000013,10-Q,1994-08-12,1994-07-01,downloaded,,not_found,
129,0000320193-94-000002,10-Q,1994-01-26,1993-12-31,downloaded,,not_found,

In [10]:
extractions_since_2006 = extractions[extractions['period_ended'] > '2005-12-31']
extractions_since_2006

,accession_number,form,filing_date,period_ended,status,error,extraction_status,extraction_error
0,0000320193-26-000020,10-Q,2026-07-31,2026-06-27,downloaded,,extracted,
1,0000320193-26-000013,10-Q,2026-05-01,2026-03-28,downloaded,,extracted,
2,0000320193-26-000006,10-Q,2026-01-30,2025-12-27,downloaded,,extracted,
3,0000320193-25-000079,10-K,2025-10-31,2025-09-27,downloaded,,extracted,
4,0000320193-25-000073,10-Q,2025-08-01,2025-06-28,downloaded,,extracted,
...,...,...,...,...,...,...,...,...
77,0001104659-07-037745,10-Q,2007-05-10,2007-03-31,downloaded,,extracted,
78,0001104659-07-006648,10-Q,2007-02-02,2006-12-30,downloaded,,extracted,
79,0001104659-06-084288,10-K,2006-12-29,2006-09-30,downloaded,,extracted,
80,0001104659-06-084286,10-Q,2006-12-29,2006-07-01,downloaded,,extracted,
81,0001104659-06-031303,10-Q,2006-05-05,2006-04-01,downloaded,,extracted,

In [14]:
failed_extractions = extractions_since_2006[extractions_since_2006['extraction_status']
                                            != 'extracted']
failed_extractions

Empty DataFrame
Columns: [accession_number, form, filing_date, period_ended, status, error, extraction_status, extraction_error]
Index: []

In [16]:
count = len(failed_extractions)
count

0

# For all compaines

In [17]:
for index in sorted(indexes_path.glob("*.csv")):
    ticker = index.stem

    extractions = pd.read_csv(index, dtype=str, keep_default_na=False)
    extractions_since_2006 = extractions[extractions['period_ended'] > '2005-12-31']
    failed_extractions = extractions_since_2006[
        extractions_since_2006['extraction_status'] != 'extracted'
        ]
    count = len(failed_extractions)

    print(ticker, count)

AAPL 0
AMZN 0
CAT 35
JNJ 62
JPM 0
KO 0
MSFT 1
NEE 0
NVDA 0
UPS 0
WMT 0
XOM 57