# Imports

In [12]:
import sys
from pathlib import Path

import pandas as pd

from src.extract_risk_factors import LocalFiling

In [13]:
# Если текущая рабочая папка — notebooks
project_root = Path.cwd().parent.parent
sys.path.insert(0, str(project_root))

# Finding extraction errors since 2006

In [14]:
project_dir = Path.cwd().parent.parent
indexes_path = project_dir / 'data' / 'indexes' / 'extraction'
cat_index = indexes_path / 'CAT.csv'
extractions = pd.read_csv(cat_index, dtype=str, keep_default_na=False)
extractions

,accession_number,form,filing_date,period_ended,status,error,extraction_status,extraction_error
0,0000018230-26-000046,10-Q,2026-08-05,2026-06-30,downloaded,,extracted,
1,0000018230-26-000021,10-Q,2026-05-06,2026-03-31,downloaded,,extracted,
2,0000018230-26-000008,10-K,2026-02-13,2025-12-31,downloaded,,extracted,
3,0000018230-25-000048,10-Q,2025-11-03,2025-09-30,downloaded,,extracted,
4,0000018230-25-000040,10-Q,2025-08-06,2025-06-30,downloaded,,extracted,
...,...,...,...,...,...,...,...,...
126,0000950131-95-000431,10-K,1995-02-23,1994-12-31,downloaded,,error,"expected string or bytes-like object, got 'Non..."
127,0000018230-94-000035,10-Q,1994-11-07,1994-09-30,downloaded,,not_found,
128,0000018230-94-000032,10-Q,1994-08-12,1994-06-30,downloaded,,not_found,
129,0000018230-94-000014,10-Q,1994-05-16,1994-03-31,downloaded,,not_found,
130,0000018230-94-000007,10-K,1994-03-02,1993-12-31,downloaded,,error,"expected string or bytes-like object, got 'Non..."

In [15]:
extractions_since_2006 = extractions[extractions['period_ended'] > '2005-12-31']
extractions_since_2006

,accession_number,form,filing_date,period_ended,status,error,extraction_status,extraction_error
0,0000018230-26-000046,10-Q,2026-08-05,2026-06-30,downloaded,,extracted,
1,0000018230-26-000021,10-Q,2026-05-06,2026-03-31,downloaded,,extracted,
2,0000018230-26-000008,10-K,2026-02-13,2025-12-31,downloaded,,extracted,
3,0000018230-25-000048,10-Q,2025-11-03,2025-09-30,downloaded,,extracted,
4,0000018230-25-000040,10-Q,2025-08-06,2025-06-30,downloaded,,extracted,
...,...,...,...,...,...,...,...,...
78,0000018230-07-000053,10-K,2007-02-23,2006-12-31,downloaded,,extracted,
79,0000018230-06-000458,10-Q,2006-11-02,2006-09-30,downloaded,,not_found,
80,0000018230-06-000382,10-Q,2006-08-02,2006-06-30,downloaded,,not_found,
81,0000018230-06-000237,10-Q,2006-05-03,2006-03-31,downloaded,,not_found,
82,0000018230-06-000139,10-K,2006-02-22,2006-02-22,downloaded,,extracted,

In [16]:
failed_extractions = extractions_since_2006[extractions_since_2006['extraction_status']
                                            != 'extracted']
failed_extractions

,accession_number,form,filing_date,period_ended,status,error,extraction_status,extraction_error
27,0000018230-19-000281,10-Q,2019-10-31,2019-09-30,downloaded,,not_found,
28,0000018230-19-000224,10-Q,2019-08-01,2019-06-30,downloaded,,not_found,
29,0000018230-19-000153,10-Q,2019-05-06,2019-03-31,downloaded,,not_found,
31,0000018230-18-000293,10-Q,2018-10-31,2018-09-30,downloaded,,not_found,
32,0000018230-18-000229,10-Q,2018-08-07,2018-06-30,downloaded,,not_found,
33,0000018230-18-000136,10-Q,2018-05-02,2018-03-31,downloaded,,not_found,
35,0000018230-17-000305,10-Q,2017-11-01,2017-09-30,downloaded,,not_found,
36,0000018230-17-000245,10-Q,2017-08-02,2017-06-30,downloaded,,not_found,
37,0000018230-17-000145,10-Q,2017-05-03,2017-03-31,downloaded,,not_found,
39,0000018230-16-000715,10-Q,2016-11-02,2016-09-30,downloaded,,not_found,
40,0000018230-16-000630,10-Q,2016-08-03,2016-06-30,downloaded,,not_found,
41,0000018230-16-000512,10-Q,2016-05-02,2016-03-31,downloaded,,not_found,
43,0000018230-15-000324,10-Q,2015-10-30,2015-09-30,downloaded,,not_found,
44,0000018230-15-000266,10-Q,2015-07-31,2015-06-30,downloaded,,not_found,
45,0000018230-15-000161,10-Q,2015-05-01,2015-03-31,downloaded,,not_found,
47,0000018230-14-000386,10-Q,2014-10-31,2014-09-30,downloaded,,not_found,
49,0000018230-14-000177,10-Q,2014-05-02,2014-03-31,downloaded,,not_found,
51,0000018230-13-000443,10-Q,2013-11-01,2013-09-30,downloaded,,not_found,
52,0000018230-13-000363,10-Q,2013-08-02,2013-06-30,downloaded,,not_found,
53,0000018230-13-000239,10-Q,2013-05-02,2013-03-31,downloaded,,not_found,
55,0000018230-12-000506,10-Q,2012-11-02,2012-09-30,downloaded,,not_found,
56,0000018230-12-000409,10-Q,2012-08-06,2012-06-30,downloaded,,not_found,
57,0000018230-12-000280,10-Q,2012-05-07,2012-03-31,downloaded,,not_found,
59,0001104659-11-060986,10-Q,2011-11-04,2011-09-30,downloaded,,not_found,
60,0001104659-11-043575,10-Q,2011-08-04,2011-06-30,downloaded,,not_found,
61,0001104659-11-027403,10-Q,2011-05-09,2011-03-31,downloaded,,not_found,
63,0001104659-10-055930,10-Q,2010-11-04,2010-09-30,downloaded,,not_found,
64,0001104659-10-040750,10-Q,2010-07-30,2010-06-30,downloaded,,not_found,
69,0000018230-09-000175,10-Q,2009-05-01,2009-03-31,downloaded,,not_found,
75,0000018230-07-000489,10-Q,2007-11-01,2007-09-30,downloaded,,not_found,
76,0000018230-07-000415,10-Q,2007-08-02,2007-06-30,downloaded,,not_found,
77,0000018230-07-000304,10-Q,2007-05-03,2007-03-31,downloaded,,not_found,
79,0000018230-06-000458,10-Q,2006-11-02,2006-09-30,downloaded,,not_found,
80,0000018230-06-000382,10-Q,2006-08-02,2006-06-30,downloaded,,not_found,
81,0000018230-06-000237,10-Q,2006-05-03,2006-03-31,downloaded,,not_found,

In [19]:
file_path = '../../data/raw/10-Q/CAT/0000018230-06-000237.txt'

In [20]:
filing = LocalFiling.from_sgml(file_path)
filing.view()

UNITED
  STATES
  SECURITIES
  AND EXCHANGE COMMISSION
  Washington,
  D.C. 20549
  FORM
  10-Q
  [X]
  QUARTERLY
  REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE
  ACT OF
  1934
  For
  the
  quarterly period ended March 31, 2006
  OR
  [
  ]
  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES
  EXCHANGE ACT OF 1934
  For
  the
  transition period from ________________ to
  ________________
 ───────────────────────────────────────────────────────────────────────────────────────────
  Commission
  File Number: 1-768
  CATERPILLAR
  INC.
  (Exact
  name
  of registrant as specified in its charter)
  Delaware                                                                     37-0602744
  (State                                                                       (IRS
  or                                                                           Employer
  other jurisdiction of incorporation)                                         I.D. No.)
  100                                                                          61629
  NE Adams                                                                     (Zip
  Street, Peoria, Illinois                                                     Code)
  (Address
  of
  principal executive offices)
  Registrant's
  telephone number, including area code:
  (309)
  675-1000
  Indicate
  by
  check mark whether the Registrant (1) has filed all reports required
  to be
  filed by Section 13 or 15(d) of the Securities Exchange Act of 1934
  during
  the preceding 12 months (or for such shorter period that the Registrant
  was required to file such reports), and (2) has been subject to such
  filing requirements for the past 90 days. Yes [ X ] No [ ]
  Indicate
  by
  check mark whether the Registrant is an accelerated filer (as defined
  in
  Rule 12b-2 of the Act). Yes [ X ] No [ ]
  Indicate
  by
  check mark whether the registrant is a large accelerated filer, an
  accelerated filer, or a non-accelerated filer. See definition of
  "accelerated filer and large accelerated filer" in Rule 12b-2 of
  the
  Exchange Act. (Check one):
  Large
  accelerated filer [ X ] Accelerated filer [
  ] Non-accelerated filer [
  ]
  Indicate
  by
  check mark whether the registrant is a shell company (as defined
  in Rule
  12b-2 of the Exchange Act). Yes [ ] No [
  X ]
  At
  March 31,
  2006, 669,630,016 shares of common stock of the Registrant were
  outstanding.

Page
1

Part
I.
FINANCIAL INFORMATION

Item
1.
Financial Statements

  Caterpillar
  Inc.
  Consolidated
  Statement of Results of Operations
  (Unaudited)
  (Dollars
  in millions except per share data)

                 Three

                 Months Ended

                 March

                 31,

                 2006                         2005
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────
  Sales
  and revenues:
                                                                          Sales
$                 8,743      $         7,789
                                                                          of
                                                                          Machinery and Engines
                                                                          Revenues
649                  550
                                                                          of
                                                                          Financial Products
                                                                          Total
9,392                8,339
                                                                          sales
                                                                          and revenues
  Operating
  costs:
                                                                          Cost
6,552                6,215
                                                                          of goods
                                                                          sold
                                                                          Selling,
821                  744
                                                                          general and administrative expenses
                                                                          Research
307                  241
                                                                          and
                                                                          development expenses
                                                                          Interest
232                  170
                                                                          expense of Financial Products
                                                                          Other
262                  213
                                                                          operating expenses
                                                                          Total
8,174                7,583
                                                                          operating costs
  Operating
1,218                  756
  profit
                                                                          Interest
68                   65
                                                                          expense excluding Financial Products
                                                                          Other
43                  108
                                                                          income
                                                                          (expense)
  Consolidated
1,193                  799
  profit before taxes
                                                                          Provision
370                  232
                                                                          for
                                                                          income taxes
                                                                          Profit
823                  567
                                                                          of
                                                                          consolidated companies
                                                                          Equity
17                   14
                                                                          in
                                                                          profit (loss) of unconsolidated
affiliated companies
  Profit
$                   840      $           581
  Profit
$                  1.25      $           .85
  per common share
  Profit
$                  1.20      $           .81
  per common share - diluted 1
  Weighted
  average common shares outstanding (millions)
                                                                          -
672.0                684.1
                                                                          Basic
                                                                          -
699.1                713.3
                                                                          Diluted 1
  Cash
$                     -      $             -
  dividends declared per common share
  1 Diluted by assumed exercise of stock options and SARs, using the
  treasury
  stock method.
  1 Diluted by assumed exercise of stock options and SARs, using the
  treasury
  stock method.
  See
  accompanying notes to Consolidated Financial
  Statements.

Page
2

  Caterpillar
  Inc.
  Consolidated
  Statement of Financial Position
  (Unaudited)
  (Dollars
  in millions)


   March


   31,


   2006
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────
  Assets
                                                    Current
                                                    assets:
                                                                                                                  C
ash
   $             806       1,108
                                                                                                                  a
nd
                                                                                                                  s
hort-term investments
                                                                                                                  R
eceivables
               8,124       7,526
                                                                                                                  -
                                                                                                                  t
rade and other
                                                                                                                  R
eceivables
               6,351       6,442
                                                                                                                  -
                                                                                                                  f
inance
                                                                                                                  D
eferred
                 345         344
                                                                                                                  a
nd
                                                                                                                  r
efundable income taxes
                                                                                                                  P
repaid
               2,150       2,146
                                                                                                                  e
xpenses
                                                                                                                  I
nventories
               5,858       5,224
                                                    Total
23,634      22,790
                                                    current
                                                    assets
                                                    Property,
7,884       7,988
                                                    plant and equipment - net
                                                    Long-term
965       1,037
                                                    receivables - trade and other
                                                    Long-term
10,550      10,301
                                                    receivables - finance
                                                    Investments
546         565
                                                    in unconsolidated affiliated companies
                                                    Deferred
760         768
                                                    income taxes
                                                    Intangible
431         424
                                                    assets
                                                    Goodwill
1,433       1,451
                                                    Other
1,754       1,745
                                                    assets
  Total
$          47,957      47,069
  assets
  Liabilities
                                                    Current
                                                    liabilities:
                                                                                                                  S
hort-term
                                                                                                                  b
orrowings:

                                                                                                       Machinery
   $             728         871

                                                                                                       and

                                                                                                       Engines

                                                                                                       Financial
               5,045       4,698

                                                                                                       Products
                                                                                                                  A
ccounts
               3,661       3,471
                                                                                                                  p
ayable
                                                                                                                  A
ccrued
               2,685       2,617
                                                                                                                  e
xpenses
                                                                                                                  A
ccrued
               1,613       1,845
                                                                                                                  w
ages, salaries and employee benefits
                                                                                                                  C
ustomer
                 520         395
                                                                                                                  a
dvances
                                                                                                                  D
ividends
                   -         168
                                                                                                                  p
ayable
                                                                                                                  D
eferred
                 722         528
                                                                                                                  a
nd
                                                                                                                  c
urrent income taxes payable
                                                                                                                  L
ong-term
                                                                                                                  d
ebt due within one year:

                                                                                                       Machinery
                 387         340

                                                                                                       and

                                                                                                       Engines

                                                                                                       Financial
               4,338       4,159

                                                                                                       Products
                                                    Total
19,699      19,092
                                                    current
                                                    liabilities
                                                    Long-term
                                                    debt due after one year:

                                          Machinery
               2,679       2,717

                                          and

                                          Engines

                                          Financial
              12,691      12,960

                                          Products
                                                    Liability
3,011       2,991
                                                    for
                                                    postemployment benefits
                                                    Deferred
915         877
                                                    income taxes and other liabilities
  Total
38,995      38,637
  liabilities
  Stockholders'
  equity
                                                    Common
                                                    stock
                                                    of $1.00 par:

                                          Authorized
               2,063       1,859

                                          shares: 900,000,000

                                          Issued

                                          shares: (3/31/06 and 12/31/05 - 814,894,624) at paid-in

                                          amount
                                                    Treasury
(5,193      (4,637
                                                    stock (3/31/06 - 145,264,608; 12/31/05 - 144,027,405) at
                                                    cost
                                                    Profit
12,648      11,808
                                                    employed in the business
                                                    Accumulated
(556        (598
                                                    other comprehensive income
  Total
8,962       8,432
  stockholders' equity
  Total
$          47,957      47,069
  liabilities and stockholders' equity
  See
  accompanying notes to Consolidated Financial
  Statements.

Page
3

  Caterpillar
  Inc.
  Consolidated
  Statement of Changes in Stockholders' Equity
  For
  the Three Months Ended
  (Unaudited)
  (Dollars
  in millions)

                                           March

                                           31,

                                           2006
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────────────────────
  Common
  stock:
                                                    Balance
$           1,859                1,231
                                                    at
                                                    beginning of period
                                                    Common
68                   46
                                                    shares
                                                    issued from treasury stock
                                                    Stock-based
34                    -
                                                    compensation expense
                                                    Tax
102                   31
                                                    benefits
                                                    from employee stock-based compensation plans
                                                    Balance
2,063                1,308
                                                    at
                                                    end of period
  Treasury
  stock:
                                                    Balance
(4,637               (3,277
                                                    at
                                                    beginning of period
                                                    Shares
182                   80
                                                    issued: 2006 - 9,212,797; 2005 - 5,264,406
                                                    Shares
(738                 (357

In [24]:
report = filing.obj()
text = report.get("Part II, Item 1A")
print(text)

None

In [25]:
output_path = indexes_path / '..' / "cat_failed.csv"
failed_extractions.to_csv(output_path, index=False, encoding="utf-8-sig")